server:
  port: 8081

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:~/data/h2/client_db;AUTO_SERVER=TRUE
    username: test  # 사용자 이름 (로그인 시 사용)
    password: 1234  # 사용자 암호 (로그인 시 사용)
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update # 해당의미?
    showSql: true

logging:
  level:
    org:
      springframework: DEBUG

oauth:
  client-id: testClientId
  client-secret: testSecret
  # scope 지정 - openid, read
  scope: read
  grant-type: authorization_code
  authentication-server-url: http://localhost:8082/oauth/token

# 클라이언트 관련 커스텀 설정
common:
  api-url: http://localhost:8080/v1/books


